services:
  db:
    build: ./db
    volumes:
      - pb_data:/pb/pb_data
    env_file:
      - .env
    restart: unless-stopped

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pb_data:
