
  create table "public"."templates" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "user_id" uuid not null default gen_random_uuid(),
    "duration" integer
      );


alter table "public"."templates" enable row level security;

CREATE UNIQUE INDEX templates_pkey ON public.templates USING btree (id);

alter table "public"."templates" add constraint "templates_pkey" PRIMARY KEY using index "templates_pkey";

alter table "public"."templates" add constraint "templates_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."templates" validate constraint "templates_user_id_fkey";

grant delete on table "public"."templates" to "anon";

grant insert on table "public"."templates" to "anon";

grant references on table "public"."templates" to "anon";

grant select on table "public"."templates" to "anon";

grant trigger on table "public"."templates" to "anon";

grant truncate on table "public"."templates" to "anon";

grant update on table "public"."templates" to "anon";

grant delete on table "public"."templates" to "authenticated";

grant insert on table "public"."templates" to "authenticated";

grant references on table "public"."templates" to "authenticated";

grant select on table "public"."templates" to "authenticated";

grant trigger on table "public"."templates" to "authenticated";

grant truncate on table "public"."templates" to "authenticated";

grant update on table "public"."templates" to "authenticated";

grant delete on table "public"."templates" to "postgres";

grant insert on table "public"."templates" to "postgres";

grant references on table "public"."templates" to "postgres";

grant select on table "public"."templates" to "postgres";

grant trigger on table "public"."templates" to "postgres";

grant truncate on table "public"."templates" to "postgres";

grant update on table "public"."templates" to "postgres";

grant delete on table "public"."templates" to "service_role";

grant insert on table "public"."templates" to "service_role";

grant references on table "public"."templates" to "service_role";

grant select on table "public"."templates" to "service_role";

grant trigger on table "public"."templates" to "service_role";

grant truncate on table "public"."templates" to "service_role";

grant update on table "public"."templates" to "service_role";


